name: ci

on: [push, pull_request]

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate tags
        id: gen_tags
        run: |
          export IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/werther"
          if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
            TAGS='"'${IMAGE}':latest","'${IMAGE}':'${GITHUB_REF/refs\/tags\//}'"'
          else
            TAGS='"'${IMAGE}':latest"'
          fi
          echo '::set-output name=tags::'$TAGS
      -
        name: Debug tags
        run:
          echo ${{ steps.gen_tags.outputs.tags }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.gen_tags.outputs.tags }}
          platforms: linux/amd64,linux/arm64/v8
